version: '3.8'

services:
  frontend:
    build:
      context: ./inventory-management-frontend
      args:
        - VITE_API_URL=http://localhost:3000/api
      no_cache: true
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./inventory-management-backend
      no_cache: true
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./inventory-management-backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
